network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
     dhcp4: true
     routes:
       - to: 192.168.50.0/24
         via: 10.42.0.1
# Place a copy of this file in /etc/netplan, this will allow the Orin to talk to the UpBoard directly via the 10.42.0.0/24 ethernet connection
