network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - 10.42.0.2/24
      gateway4: 10.42.0.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
# Place a copy of this file in /etc/netplan, this will allow the Orin to talk to the UpBoard directly
